### ISSUE TITLE
Communications - slack, gitter, discord, irc?

### ISSUE THREAD

**Issue by ToeiRei** [burmilla/os#10]
Hi guys,

I was thinking about some community chat to make development easier and enabling us to evaluate some stuff a bit more efficient instead of going back and forward on github issues (not saying that issues shouldn't be there - just that they are not the right medium for 'chatter')

**Comment by olljanat** [comment]
Sure. Let's vote about tool.

Please leave one of these reactions to this message (and comment below if we need more options)
- Slack :smile:
- Gitter :tada:
- Discord :heart: 
- IRC :rocket: 
- Telegram :eyes:

**Comment by PrplHaz4** [comment]
IRC or Matrix (both more "open" than the others) - I won't have much to contribute, but I hate seeing user-hostile proprietary platforms proliferating for open source projects...

**Comment by olljanat** [comment]
Matrix was new one to me but it looks interesting option and I can see that example Mozilla [have moved from IRC to Matrix](https://wiki.mozilla.org/Matrix).

I added Matrix to options and actually already created `#burmillaos:matrix.org` so we can test it.

**Comment by tomaswarynyca** [comment]
For me we can use Discord since I think almost all of us have an account there and we can make a good management of the channels to organize everything related to burmillaOS. If you are interested I can take care of creating and managing the channel.

**Comment by ToeiRei** [comment]
Best thing about Discord would be integrated voice

**Comment by olljanat** [comment]
> If you are interested I can take care of creating and managing the channel.

Yes I'm happy to give you that task :smile: Then we can do with Discord.

> Best thing about Discord would be integrated voice

Yea it is good option to have but I'm not yet sure if I want to have voice calls about BurmillsOS as I have those enough already on work and because discussion and decisions made on those are not visible for community.

**Comment by tomaswarynyca** [comment]
> Yes I'm happy to give you that task smile Then we can do with Discord.

Great! In the next few hours I will plan the structure that the server will have. The idea is to have a space to talk more quietly and then put in GitHub all the problems or discussions for the community to contribute.

**Comment by ToeiRei** [comment]
@olljanat voice is for me something when you're working on a specific issue. It sure is not a tool for global decisions. For me it replaces that coffee talk to get me unstuck on some issues...

**Comment by tomaswarynyca** [comment]
Well, I leave the link of Discord for you to join us we are in a stage of beta server to finish polishing.
https://bit.ly/DiscordBurmillaOS

**Comment by olljanat** [comment]
I think that we should cross link all documentation and documents on pages.

So we need:
- Update readme on master branch to contain links to documentation and Discord
- Update documentation containing link to here and Discord

**Comment by pwFoo** [comment]
Also a simple web forum would be nice?

**Comment by olljanat** [comment]
> Also a simple web forum would be nice?

I'm not necessarily against of it but still wonder that if that make sense until Burmilla community grow.

**Comment by ToeiRei** [comment]
I believe what pwFoo maybe wants to say is that a forum may attract more people.

**Comment by olljanat** [comment]
> I believe what pwFoo maybe wants to say is that a forum may attract more people.

It might be but on this phase it is much more important to find enough people who will contribute the project on here on GitHub and more we have those alternative communication methods less likely people will find their way here.

This issue is good example of case where almost anyone would be able to help by just taking action and handling those final steps mentioned on https://github.com/burmilla/os/issues/10#issuecomment-745631752

**Comment by pwFoo** [comment]
Maybe activate discussion feature instead of a forum / external tool?

**Comment by wonleing** [comment]
> Well, I leave the link of Discord for you to join us we are in a stage of beta server to finish polishing.
> https://bit.ly/DiscordBurmillaOS

Is it still available? I can not open it, but https://bit.ly works.

**Comment by olljanat** [comment]
@tomaswarynyca what happened to our Discord link?

**Comment by tomaswarynyca** [comment]
@wonleing You can try again, it works perfectly for me.

**Comment by wonleing** [comment]
Just joined as "wonleing". But I don't have privilege to leave a message there

**Comment by tomaswarynyca** [comment]
> Just joined as "wonleing". But I don't have privilege to leave a message there

You have the same permissions as the others, keep in mind that some of them are restricted. 
I just mentioned it to see if you can write in the channels without restrictions.
