### ISSUE TITLE
BurmillaOS arm64 architecture installation bare metal can not use the mouse and keyboard！

### ISSUE THREAD

**Issue by newhuangchuan** [burmilla/os#104]
**BurmillaOS Version: (ros os version)**
v2.0.0-beta4
**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal
**Which processor architecture you are using?**
arm64
**Do you use some extra hardware? (GPU, etc)?**
no
**Which console you use (default, ubuntu, centos, etc..)**
ubuntu
**Do you use some service(s) which are not enabled by default?**
no
**Have you installed some extra tools to console?**
no
**Do you use some other customizations?**
no
**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
<replace with sudo ros config export output>
```
Hello, I used the bate4 version of burmillaOS to build the ISO file of arm64. After the build was successful, after adding the grub and efi files, burn the ISO file to the U disk, install the system on the arm64 physical server, and the mouse and keyboard will appear Unavailable. The picture shows the USB device reading process during the kernel loading process, and information about KVM appears in it. Do you have any views on this issue here?
![image](https://user-images.githubusercontent.com/53457306/123566298-ef7d7980-d7f1-11eb-8d13-67a5b9a448b0.png)

**Comment by olljanat** [comment]
I would guess missing or broken driver but hard to say for sure.

**Comment by newhuangchuan** [comment]
The kernel code is recompiled, and the USB drivers have been installed. Then go to the physical machine to install, or go back to detect the kvm device.
