### ISSUE TITLE
How to make a new burmilla kernel-config base on standard Linux kernel config?

### ISSUE THREAD

**Issue by wonleing** [burmilla/os#105]
In order to support some specific arm machine, We have to build burmilla kernel base on our own standard Linux kernel source and config. But the result is it report "error: out of memory" during system boot.
My question is: How to make a new burmilla kernel-config base on a standard Linux kernel config? Any step to cut the size to a burmilla like one?

**Comment by olljanat** [comment]
Most probably issue is that standard config includes too much drivers which why kernel and/or initrd gets too big. Disabling drivers which you do not need should helps.
