### ISSUE TITLE
Suggestion: Remove versioning numbers from release iso files

### ISSUE THREAD

**Issue by DanielNagy** [burmilla/os#109]
Please remove the version number from filename of the release files so that we can utilise the "latest" tag when pulling iso's.

ie, so the following URL works.
https://github.com/burmilla/os/releases/download/latest/burmillaos-vmware.iso

RancherOS had no versioning in the filename. Older released can be referenced by different URL.

**Comment by olljanat** [comment]
> RancherOS had no versioning in the filename. Older released can be referenced by different URL.

Yes RancherOS used that bad practice where every time download new ISO version you need to add version to its name to be able to separate different versions and its format depends about who have done that. 

Example on our environment I can see files like:
* rancheros_1.5.1.iso
* rancheros-v1.5.2.iso
* rancheros_v1.5.5.iso

That why I updated release script on way that those will include version number to file names on standardized format.
