### ISSUE TITLE
Documentation needs navigation

### ISSUE THREAD

**Issue by olljanat** [burmilla/os#11]
RancherOS documentation have been copied and update to use term BurmillaOS on https://github.com/burmilla/burmilla.github.io
Those files are using GitHub markup and they are published as GitHub Pages to https://burmillaos.org
Issue however is that when I removed Rancher layout from documentation we lost side navigation which why it is very hard find anything from those documents.

That why we should investigate how to implement navigation to GitHub Pages.

**Comment by tomaswarynyca** [comment]
Don't you think it's a good idea to migrate the BurmillaOS documentation to **gitbook**?

**Comment by ToeiRei** [comment]
@tomaswarynyca pricing is an issue here.

**Comment by olljanat** [comment]
Yea. We definitely want to stay on those solutions which are free for open source projects.

**Comment by ToeiRei** [comment]
We need a different template with a sidebar or we'll generate HTML files locally and upload them.

**Comment by olljanat** [comment]
Afaiu one quite common practise is create separate "gh-pages" branch and change GitHub Pages to use it instead of master.

Then we can have GitHub Actions CI which generates static files and publish them to "gh-pages" branch with https://github.com/marketplace/actions/github-pages to publish

**Comment by tomaswarynyca** [comment]
We could use vuejs, I found this add-on that would look great for documentation
https://vuesax.com/

**Comment by olljanat** [comment]
@tomaswarynyca I'm not familiar with vuejs but IMO we should avoid any solution which requires us to re-write whole documentation. Also I really like that documentation are done with pure GitHub markup which is easy to modify and keep version history.

@ToeiRei I see that you have tried to get external themes working. You most probably can do it on CI like it is described on https://github.com/vjeantet/hugo-theme-docdock#1-install-docdock-as-git-submodule

**Comment by olljanat** [comment]
I created test version to https://github.com/olljanat/burmilla.github.io/tree/use-hugo and generated "publish version" with "hugo" command to https://github.com/olljanat/burmilla.github.io/tree/gh-pages which is hosted on https://olljanat.github.io/burmilla.github.io

Looks that I miss some Hugo basics so it does not generate HTML files yet but I leave this comment here anyone in case you find useful info from it. Hugo templates deploy process to GitHub Pages is described on https://gohugo.io/hosting-and-deployment/hosting-on-github/

**Comment by tomaswarynyca** [comment]
What do you think about using this template?
https://themes.gohugo.io/hugo-book/
It already has the structure to be multilingual

**Comment by olljanat** [comment]
> What do you think about using this template?
> https://themes.gohugo.io/hugo-book/
> It already has the structure to be multilingual

Looks very good option IMO.

**Comment by dgiebert** [comment]
Already worked with Hugo today, so I can have a draft using the hugo-book theme

**Comment by olljanat** [comment]
@dgiebert yes please :+1:

**Comment by olljanat** [comment]
Solved by https://github.com/burmilla/burmilla.github.io/pull/2
