### ISSUE TITLE
Unable to boot from USB drive on RPi 4B

### ISSUE THREAD

**Issue by simonnilsson** [burmilla/os#110]
**BurmillaOS Version: (ros os version)**
v2.0.0-beta4

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Raspberry Pi 4B (8GB)

**Which processor architecture you are using?**
arm64

**Do you use some extra hardware? (GPU, etc)?**
USB3 boot drive

Boot process gets stuck at `Waiting for root device /dev/mmcblk0p2` which i believe is the SD card that is not present since I'm booting for a USB3 flash drive. Any way to get around this?

**Comment by olljanat** [comment]
Based on https://github.com/burmilla/os/blob/0dc7a00e0e8ccae1b8492214e0d97a7e229fd8e2/scripts/images/raspberry-pi-hypriot64/scripts/build.sh#L66
there is `/dev/mmcblk0p2` on cmdline.txt which you most probably need updating pointing to `/dev/sda2`

Look: https://www.raspberrypi.org/documentation/computers/configuration.html#the-kernel-command-line

**Comment by simonnilsson** [comment]
Yes that did it, thanks!

I also noticed that the password for the default rancher user is defined here. Maybe this should be added to the documentation?
