### ISSUE TITLE
Crontab seems not to work

### ISSUE THREAD

**Issue by jokay** [burmilla/os#113]
**BurmillaOS Version: (ros os version)**

[1.9.2](https://github.com/burmilla/os/releases/tag/v1.9.2)

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**

VM on [ProxmoxVE](https://www.proxmox.com/en/proxmox-ve)

**Which processor architecture you are using?**

amd64

**Do you use some extra hardware? (GPU, etc)?**

no

**Which console you use (default, ubuntu, centos, etc..)**

default

**Do you use some service(s) which are not enabled by default?**

- qemu-guest-agent
- crontab

**Have you installed some extra tools to console?**

no

**Do you use some other customizations?**

no

---

I enabled crontab as service but the command is still not usable.

```sh
disabled amazon-ecs-agent
disabled container-cron
disabled zfs
disabled kernel-extras
disabled kernel-headers
disabled kernel-headers-system-docker
disabled open-vm-tools
disabled hyperv-vm-tools
enabled  qemu-guest-agent
disabled amazon-metadata
disabled volume-cifs
disabled volume-efs
disabled volume-nfs
disabled modem-manager
disabled waagent
disabled virtualbox-tools
enabled  docker-compose
enabled  crontab
```

When I execute:

```sh
sudo mkdir -p /var/spool/cron/crontabs
sudo crond
sudo crontab -e
```

It fails ... `crontab: command not found`

There is no `/usr/bin/crontab` in BurmillaOS like in RancherOS.

**Comment by olljanat** [comment]
crontab service is system container which usage is explained on https://burmillaos.org/docs/system-services/custom-system-services/#cron and https://github.com/burmilla/container-crontab#examples and we have not changed those.

On which console you did see `/usr/bin/crontab` on RancherOS? It must be separate thing.

As workaround you most probably can install cron to console with commands:
```
sudo sed -i -e 's/stable/buster/' /etc/apt/sources.list
sudo apt-get update
sudo apt-get install cron

```

**Comment by jokay** [comment]
> On which console you did see `/usr/bin/crontab` on RancherOS? It must be separate thing.

The default console.

I only use **crontab** to execute commands and never **container-crontab**, thx for the clarification.

**Comment by jokay** [comment]
> ```sh
> sudo sed -i -e 's/stable/buster/' /etc/apt/sources.list
> sudo apt-get update
> sudo apt-get install cron
> ```

Will this "survive" a `sudo ros os upgrade` or do we need to re-install this on each upgrade?

**Comment by olljanat** [comment]
> Will this "survive" a `sudo ros os upgrade` or do we need to re-install this on each upgrade?

No, that why it called for workaround

**Comment by jokay** [comment]
Issue closed, thx for clarification.
