### ISSUE TITLE
Avaibility of AMI in AWS

### ISSUE THREAD

**Issue by thorstenthomsen** [burmilla/os#114]
**BurmillaOS Version: (ros os version)**
1.9.2

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

**Which processor architecture you are using?**
amd64

**Do you use some extra hardware? (GPU, etc)?**
no

**Which console you use (default, ubuntu, centos, etc..)**
default

**Do you use some service(s) which are not enabled by default?**
no

**Have you installed some extra tools to console?**
no

**Do you use some other customizations?**
no

I can't find AMI's in Amazon cloud. When will they be available?

**Comment by olljanat** [comment]
Look https://github.com/burmilla/os/issues/55#issuecomment-770342781
