### ISSUE TITLE
Proposal: Switch v2.0 versions to use same base as RancherOS v2

### ISSUE THREAD

**Issue by olljanat** [burmilla/os#119]
Continuation to #88 but with different approach.

It looks to be sure now that we will see [RancherOS v2](https://rancher.github.io/os2/) and in the fact first test version is already available on https://github.com/rancher/os2/releases/tag/v0.0.1-test01 but as their strategy is support Kubernetes only there is still room for BurmillaOS.

As we have not ever released anything else than beta versions under v2.0 schema can still change architecture for it. So I created prototype version to https://github.com/burmilla/os2/releases/tag/v0.0.1-test01-burmilla which contains Docker instead of Kubernetes.

What is interesting is that they have ended up to quite similar solution than which I proposed on https://github.com/burmilla/os/issues/88#issuecomment-839804934 with two root partitions and read-only overlay on top of it.

This approach would:
* Simplify maintenance work as most of the code would be common with them.
* Add UEFI support #8
* Be clear answer to  #47 and we can instruct all Kubernetes users to use RancherOS v2 instead of BurmillaOS.

Biggest open question is that how much work is needed to make `ros upgrade` working with that one and create migration/upgrade path. (Partial solution already exist on https://rancher-sandbox.github.io/cos-toolkit-docs/docs/getting-started/upgrading/ )

**Comment by PrplHaz4** [comment]
This sounds like a sensible approach that does a good job of balancing features and maintainability.

**Comment by olljanat** [comment]
RancherOS v2 looks to be stuck on alpha phase but now SUSE released this one as beta which we probably should investigate? https://news.opensuse.org/2022/04/05/leap-micro-beta-available-for-testers/

**Comment by PrplHaz4** [comment]
> RancherOS v2 looks to be stuck on alpha phase but now SUSE released this one as beta which we probably should investigate? https://news.opensuse.org/2022/04/05/leap-micro-beta-available-for-testers/

The Harvester docs replaced K3OS with Elemental ~6mos ago.  As this was (I think?) the impetus for RancherOS 2 (which was just tagged with another release today) it may be premature to remove that option.  Also, os2 feels more open/accessible than Leap but that could be me not really understanding the OpenSuse way...

**Comment by olljanat** [comment]
> The Harvester docs replaced K3OS with Elemental ~6mos ago. As this was (I think?) the impetus for RancherOS 2 (which was just tagged with another release today) it may be premature to remove that option.

True. On https://github.com/harvester/os2 it looks to be still updating.  However it is also based on openSuse Leap https://github.com/harvester/os2/blob/ae38642196eedbd919a984f3aa89c72800f14599/Dockerfile#L3

> Also, os2 feels more open/accessible than Leap but that could be me not really understanding the OpenSuse way...

Yes that is quite big disadvantage. Bugs need to be reported using Bugzilla and I found source codes as rpm packages only. However as Rancher is now part of Suse it is clear that they are looking for sharing best practices so let's hope that Suse will be more open in future.

**Comment by PrplHaz4** [comment]
Move to suse leap micro for harvester looks to be official now 

https://github.com/harvester/os2/pull/40

**Comment by olljanat** [comment]
Yea and they looks to be renamed RancherOS v2 to Elemental which development continues on https://github.com/rancher/elemental

**Comment by olljanat** [comment]
Closing for now as no one is working on this area.
