### ISSUE TITLE
Update to buildroot 2020.02.8

### ISSUE THREAD

**Issue by olljanat** [burmilla/os#12]
Currently [os-base](https://github.com/burmilla/os-base) and [os-initrd-base](https://github.com/burmilla/os-initrd-base) uses quite old buildroot 2018.02.11-1.

We should update to latest LTS version which currently is 2020.02.8

Full change log between those versions:
https://github.com/buildroot/buildroot/blob/00e80cb1769047ad8c768d35003ae68fb4c3b0f0/CHANGES#L643-L3277

I have already made test configs to os-base/os-initrd-base with latest stable (not LTS) version 2020.08.1 but looks that something went wrong on config updates because OS build with that one will end up to Kernel panic on boot.

**Comment by ToeiRei** [comment]
Can you get me the kernel panic? Maybe I can figure something...

btw - I have a drone server here that could do some automated builds. It's not the fastest machine in the world, but it gets the job done.

**Comment by olljanat** [comment]
It reboots after 10 seconds but I managed take picture of it:
![20201121_082052](https://user-images.githubusercontent.com/6213926/99869379-34459000-2bd3-11eb-8419-c519fd13668c.jpg)

I got all amd64 builds working with GitHub actions already and arm64 I can build on raspberry so there is no need for drone.

**Comment by olljanat** [comment]
Looks that I got this working on latest versions of os-base and os-initrd-base.
