### ISSUE TITLE
iGPU/i915 driver 

### ISSUE THREAD

**Issue by xh116** [burmilla/os#124]
Thanks for Burmilla project. 

I just installed it in ESXi  and passthroughed intel graphic as media server decoding. 
But it seems no drivers for it.
Is there any way to add it or just need to enable it somewhere? 

![image](https://user-images.githubusercontent.com/37950502/146794053-6d218bb8-a40d-4bc7-be88-8a036aeb50b7.png)

**Comment by olljanat** [comment]
It looks to be listed on https://github.com/burmilla/os-kernel/blob/v4.14.x/modules/x86/modules-extra.list#L224 so enabling kernel extras should help. Look https://burmillaos.org/docs/configuration/kernel/loading-kernel-modules/#loading-extra-kernel-modules

**Comment by xh116** [comment]
> It looks to be listed on https://github.com/burmilla/os-kernel/blob/v4.14.x/modules/x86/modules-extra.list#L224 so enabling kernel extras should help. Look https://burmillaos.org/docs/configuration/kernel/loading-kernel-modules/#loading-extra-kernel-modules

That's it! 
It works now. 
Thanks!

**Comment by olljanat** [comment]
Good 👍

**Comment by xh116** [comment]
By the way, It seems there is problem with nfs mounting ? 
`sudo mount -t nfs4 10.0.0.66:/mnt/Pool01/Media /mnt/media`
`mount: /mnt/media: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.`

I am sure it worked in other linux system.
