### ISSUE TITLE
NFS mounting 

### ISSUE THREAD

**Issue by xh116** [burmilla/os#125]
By the way, It seems there is problem with nfs mounting ?
```
sudo mount -t nfs4 10.0.0.66:/mnt/Pool01/Media /mnt/media
mount: /mnt/media: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```
I am sure it worked in other linux system.

I also tried to enable volume-nfs but it doesnt help. 
sudo ros service enable volume-nfs 

any suggestions?

**Comment by olljanat** [comment]
Look https://github.com/burmilla/os/issues/40#issuecomment-754125942
