### ISSUE TITLE
Making console container customizable

### ISSUE THREAD

**Issue by benok** [burmilla/os#126]
Hi, again.

I noticed that current default(debian) console doesn't install man pages. 
It was installed on the debian console of rancheros.

I found It's because Burmilla's debian container is based on **-slim** image.
But I want to use BurmillaOS for personal **development** server.
So I need man page sometimes.

_Slim image is for container image, not for console.
So, it's suitable alternative for rancheros's "default" console, 
but I need "(plain)debian" if so._

Anyway, how to customize default console ?
We can modify [Dockerfile ](https://github.com/burmilla/os/blob/master/images/02-console/Dockerfile) and build image.
But how to install that container ? 
Is it easy at this moment ?

p.s.
I think it's useful if we can override install source of console container.
I prefer not using custom docker registry, but specify source repository of console container image.

For example, 
```yaml
console: build
console-repository: https://github.com/someone/my-custom-console
```
clones user's repo & build customized console image on installation.  

Isn't that cool ?  :-)

**Comment by olljanat** [comment]
One reason why we switched default console to Debian based is that now you can use `apt-get` to install additional packages.

Alternatively you can build totally customized console like it is described on https://burmillaos.org/docs/installation/custom-builds/custom-console/

**Comment by benok** [comment]
I'm sorry for the late response.

>One reason why we switched default console to Debian based is that now you can use apt-get to install additional packages.

I'm afraid I think you misunderstand my point.

I'm using the Debian console from the beginning when I started to use rancheros.

I don't want to repeat what I wrote but, Debian's **-slim** container is not suitable for console container.
Rancher didn't use -slim image.  I believe -slim for the console is not suitable for human use.
*-slim image is built to use inside some app containers.

For example, it didn't install man page even though an additional package has man page inside.
It's defined by *-slim image's dpkg configuration.

> Alternatively you can build totally customized console like it is described on
> https://burmillaos.org/docs/installation/custom-builds/custom-console/

Did you really read the page above?
It doesn't describe how to build a customized console. 
Just to describe how to switch available consoles and those which are not available anymore.

I'm happy with Debian console because I'm a Debian user.
But the people who love Centos or Ubuntu don't want to use Debian console, right?

I prefer we can build & use our own console.
That's what I want to write on this ticket.

**Comment by benok** [comment]
OK, I found the documentation about this below.
https://burmillaos.org/docs/system-services/custom-system-services/#creating-your-own-console

Also, I've  read  implementations around these and 
perhaps, I understand how to build & use my own image.

I haven't tried yet, but it seems I can even use rancher os's console images like below.
```yml
rancher:
  repositories:
    console:
      url: https://raw.githubusercontent.com/rancher/os-services/master
```

It requires pushing image to docker repository.
I feel it's not handy but implementing custom image build is a bit complicated (i.e. it requires git).
If I'm not satisfied with the current method, I might try to implement this.

**Comment by olljanat** [comment]
Yes it should be possible to use RancherOS consoles on also. And used architecture heavily utilises docker registry so you need to have one.

What comes to Debian vs Debian slim it mostly just define starting point. You should be able to change dpkg config on way that man pages gets included before installing additional packages.

**Comment by benok** [comment]
Hi, now I published this.
https://github.com/benok/burmilla-os-console
Could you please take a look?

**Comment by olljanat** [comment]
Looks good method for me. Now you can support whatever special consoles you need and we don't need support them on there.

If you want you can also open pull request which adds link to your project to https://github.com/burmilla/burmilla.github.io/blob/master/content/docs/installation/custom-builds/custom-console.md

**Comment by benok** [comment]
Thank you for your comment.

> If you want you can also open pull request which adds link to your project to 
> https://github.com/burmilla/burmilla.github.io/blob/master/content/docs/installation/custom-builds/custom-console.md

OK, I want to do this within this week.

**Comment by benok** [comment]
Hi, I'm sorry tooooo be late. :-)

I've recently updated my unofficial custom console images.

I updated Alpine, Ubuntu,  Fedora to `latest`, and checked these consoles a little bit, and I found no problems.

(But currently, only tested within v2.0.0-beta5, though.)

And also submitted the doc's [pull request](https://github.com/benok/burmilla.github.io/pull/1).
