### ISSUE TITLE
v1.9.0-beta2 known issues

### ISSUE THREAD

**Issue by olljanat** [burmilla/os#13]
I noticed couple new issues on v1.9.0-beta2 which need to be fixed on release candidate.

I will add those as one issue per comment and other can do same.

**Comment by olljanat** [comment]
Way how I tried optimize Debian console disk usage by removing extra locales on https://github.com/burmilla/os-services/blob/f8f361e8d7fbef94c971dd707f0e2a96ac0bdc88/images/10-debianconsole/Dockerfile#L12-L14 is no very smart and it generates new error messages like this:
```
rancher@burmilla:~$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
Most probably logic must be that we keep all locales which exist on debian:stable-slim and include en_US.UTF-8 from locales package (or just forgot that optimization).

**Comment by olljanat** [comment]
Default console still exists even when I tried to make Debian as only console. Most probably I need move files from https://github.com/burmilla/os-services/tree/f8f361e8d7fbef94c971dd707f0e2a96ac0bdc88/images/10-debianconsole to https://github.com/burmilla/os/tree/v1.9.x/images/02-console

Good think on that would be that is simplify also build process as currently I need build console with same version tag first that OS build can include it to ISO file.

**Comment by olljanat** [comment]
ros command currently only list Rancher Labs as only author. "Project Burmilla" should be there too like we have now on readme files.
```
[rancher@burmilla ~]$ sudo ros
NAME:
   ros - Control and configure BurmillaOS
built: '2020-11-17T21:19:11Z'

USAGE:
   ros [global options] command [command options] [arguments...]
   
VERSION:
   v1.9.0-beta2
   
AUTHOR(S):
   Rancher Labs, Inc. 
```

**Comment by olljanat** [comment]
Not actually new issue but visible because Debian is default console now.

RancherOS default console print line which starts with text "docker-sys" and contains eth0 IP address which is very useful when deploying servers with DHCP and you want to know which IP they got.

**Comment by olljanat** [comment]
Currently user must switch to Debian console before upgrading from RancherOS (like I updated to guidance). Other why it generates a lot of errors.

**Comment by olljanat** [comment]
VMware tools does not work
![image](https://user-images.githubusercontent.com/6213926/99872365-fef86c80-2be9-11eb-9e18-dd45ed6587b1.png)

**Comment by olljanat** [comment]
First boot from ISO and from disk on Proxmox VE gets stuck to this view for one minute:
![20201121_112943](https://user-images.githubusercontent.com/6213926/99874037-2ac92180-2bed-11eb-8e18-401481ad951b.jpg)

It does not happen on RancherOS 1.5.6.

Second boot works fine on BurmillaOS too.

**Comment by tomaswarynyca** [comment]
It is not possible to use the iso burmillaos-v1.9.0-beta2 with a docker-machine

```
docker-machine create -d virtualbox --virtualbox-boot2docker-url https://bit.ly/3lSbRPu burmilla

Running pre-create checks...
Creating machine...
(burmilla) Downloading from https://bit.ly/3lSbRPu...
(burmilla) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(burmilla) Creating VirtualBox VM...
(burmilla) Creating SSH key...
(burmilla) Starting the VM...
(burmilla) Check network to re-create if needed...
(burmilla) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Error creating machine: Error detecting OS: OS type not recognized
```
When I turn off the machine, turn it back on and list the available machines I realize that I get the following error

```
docker-machine start burmilla
Starting "burmilla"...
(burmilla) Check network to re-create if needed...
(burmilla) Waiting for an IP...
Machine "burmilla" was started.
Waiting for SSH to be available...
Detecting the provisioner...
OS type not recognized
```
```
docker-machine ls
 ERRORS Unable to query docker version: Cannot connect to the docker engine endpoint
```

**Comment by olljanat** [comment]
> It is not possible to use the iso burmillaos-v1.9.0-beta2 with a docker-machine

Yes, with quick look of their code. docker-machine reads file `/etc/os-release` which is generated on:
https://github.com/burmilla/os/blob/5a13f03a29a041ca65d2d6f5c25fb7f1a92b0222/scripts/layout-initrd#L36-L47
we must restore **ID** value to `rancheros`

**Comment by tomaswarynyca** [comment]
If you run the command with the -D argument you will be able to see what happens when the virtual machine is created. We can see that the error is in BUILD_ID

`docker-machine -D create -d virtualbox --virtualbox-boot2docker-url https://bit.ly/3lSbRPu burmilla`

```
cat /etc/os-release
SSH cmd err, output: <nil>: NAME="BurmillaOS"
VERSION=v1.9.0-beta2
ID=burmillaos
ID_LIKE=
VERSION_ID=v1.9.0-beta2
PRETTY_NAME="BurmillaOS v1.9.0-beta2"
HOME_URL="https://burmilla.github.io"
SUPPORT_URL="https://github.com/burmilla/os/issues"
BUG_REPORT_URL="https://github.com/burmilla/os/issues"
BUILD_ID=

Couldn't set key BUILD_ID, no corresponding struct field found
Error creating machine: Error detecting OS: OS type not recognized
notifying bugsnag: [Error creating machine: Error detecting OS: OS type not recognized]
```

**Comment by olljanat** [comment]
@tomaswarynyca BUILD_ID is empty on RancherOS too so I'm quite sure that ID is key thing here. Anyway, can you try with rc1 draft version before I make it public? You should see it when you are logged in.

**Comment by tomaswarynyca** [comment]
@olljanat You are right I was testing the version v1.9.0-rc1 and it works perfectly in docker-machine.

The only thing you can see is that our `BulminaOS /v /n /l` at startup. Is it correct that I show that?
![VirtualBox_burmilla_23_11_2020_11_14_50](https://user-images.githubusercontent.com/41587659/99972428-43684180-2d7d-11eb-9a98-b58c91b852a4.png)

**Comment by olljanat** [comment]
@tomaswarynyca hmm. true. RancherOS replace those with some system infos. Need to investigate how we get those in-place.

Anyway, other bugs looks to be fixed so I made rc1 public now.

**Comment by olljanat** [comment]
Let's try finalize v1.9.0 so I will close this one now and separate issue from each problem which still exist/can be found from rc1.
