### ISSUE TITLE
/opt/burmilla/bin/start.sh not getting executed

### ISSUE THREAD

**Issue by drorgl** [burmilla/os#145]
**BurmillaOS Version: (ros os version)** 1.9.5

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)** docker-machine / virtualbox

**Which processor architecture you are using?** Kaby Lake

**Do you use some extra hardware? (GPU, etc)?** No

**Which console you use (default, ubuntu, centos, etc..)** default

**Do you use some service(s) which are not enabled by default?** VirtualBox Guest Additions

**Have you installed some extra tools to console?** Yes, bzip2 tar gcc make perl

**Do you use some other customizations?** Install VirtualBox Guest Additions, see below

**Please share copy of your cloud-init (remember remove all sensitive data first)** 
default

I'm attempting to set a docker environment through docker-machine in VirtualBox.

I've failed to mount through:
```
sudo ros service enable virtualbox-tools
sudo ros service up virtualbox-tools
mount.vboxsf d /d
```

So I've setup the VirtualBox Guest additions as follows:
```
sudo apt install bzip2 tar gcc make perl
sudo mount /dev/sr1 /mnt
cd /mnt
sudo ros service enable kernel-headers
sudo ros service up kernel-headers
sudo ./VBoxLinuxAdditions.run
```

And mount a VirtualBox Shared Folder as follows:
```
sudo mkdir /d
sudo chmod 777 /d
sudo mount -t vboxsf -o defaults,uid=`id -u docker`,gid=`id -g docker` d /d
```

The mount works.

I'm having issues with setting up an automatic mount, I've attempted to run the mount through the following but it caused a boot loop with kernel panic.
```
ros config set mounts '[["d","/d","vboxsf",""]]'
```

So I attempted to use the `/opt/burmilla/bin/start.sh` but nothing happens.
```
mkdir -p /opt/burmilla/bin
edit /opt/burmilla/bin/start.sh and add sudo mount -t vboxsf -o defaults,uid=`id -u docker`,gid=`id -g docker` d /d
sudo chmod 755 /opt/burmilla/bin/start.sh
```

I can't see anything in the logs, how can I debug it?

I've also attempted to modify fstab but it didn't work either.

Thank you.

**Comment by olljanat** [comment]
Shared folders have not been really supported with VirtualBox. If we want to support it we should first figure how how to get vbox tools updated to latest version (build fails after PR https://github.com/burmilla/os-services/pull/17)

Also https://github.com/burmilla/os-services/blob/master/images/10-vboxtools/Dockerfile most likely need to be updated to get those vbox guest tools to console.

I'm ready to accept pull requests if someone implements those but most likely will no have time to investigate this my self.

**Comment by olljanat** [comment]
It is bug but closing because looks that there is no many VirtualBox users nowadays anymore.
