### ISSUE TITLE
S alternatives

### ISSUE THREAD

**Issue by DelfsEngineering** [burmilla/os#147]
**BurmillaOS Version: (ros os version)**

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**

**Which processor architecture you are using?**

**Do you use some extra hardware? (GPU, etc)?**

**Which console you use (default, ubuntu, centos, etc..)**

**Do you use some service(s) which are not enabled by default?**

**Have you installed some extra tools to console?**

**Do you use some other customizations?**

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
<replace with sudo ros config export output>
```

**Comment by olljanat** [comment]
@DelfsEngineering ?
