### ISSUE TITLE
Kernel 4.14.x EOL in January 2024

### ISSUE THREAD

**Issue by olljanat** [burmilla/os#148]
Kernel 4.14.x versions used by Burmilla OS 1.9.x versions will reach end of life on January 2024 https://kernel.org/category/releases.html

Kernel 5.10.x versions used by Burmilla OS 2.0.x versions looks to be supported until December 2026 so I think that it is time to try get release version out of it during this spring and then people have half of the year update their systems.

**Comment by PrplHaz4** [comment]
Great plan - thank you for taking care of us!

**Comment by olljanat** [comment]
Closing because [v2.0.0-rc1](https://github.com/burmilla/os/releases/tag/v2.0.0-rc1) was released.
