### ISSUE TITLE
VDSL2 / ppp Network Support?

### ISSUE THREAD

**Issue by pwFoo** [burmilla/os#153]
I know in the past RancherOS doesn't support VDSL2 / ppp network. RancherOS haven't the needed kernel modules.
Is it possible to add needed kernel modules and support PPP / VDSL network connections?

**Comment by olljanat** [comment]
Kernel modules we can get by updating https://github.com/burmilla/os-kernel/blob/master/config/x86/kernel-config and either of files in https://github.com/burmilla/os-kernel/tree/master/modules/x86 (depending if we want those to be included to iso file or just kernel extras).

However I wonder that which kind of configuration those needs because probably we need add some logic to network system container too.

Also from I'm curious about that which kind of use case you are thinking here? Using BurmillaOS as home router with some set of containers? With which kind of hardware?

**Comment by pwFoo** [comment]
Yes, a home server / router as first task, but as location firewall / server in mind.

Hardware APU / IPU boards from pcengines for example.

**Comment by olljanat** [comment]
@pwFoo ok. do you know which drivers are needed for those?

**Comment by pwFoo** [comment]
Hi @olljanat 
here a roughly filtered kernel module list with 
```
amd_xgbe              114688  0 
bnx2                   73728  0 
crc_ccitt              12288  1 ppp_async
e1000                  98304  0 
e1000e                176128  0 
ena                    69632  0 
forcedeth              61440  0 
i2c_dev                12288  0 
igb                   159744  0 
igc                    77824  0 
ip6_tunnel             32768  0 
ixgbe                 212992  0 
mdio                   12288  1 ixgbe
mii                    12288  0 
nls_cp437              16384  0 
nls_iso8859_1          12288  0 
nls_utf8               12288  0 
ppp_async              16384  0 
ppp_generic            28672  7 pppoe,ppp_async,pppox
pppoe                  16384  2 
pppox                  12288  1 pppoe
pps_core               12288  1 ptp
ptp                    20480  6 igc,e1000e,ixgbe,amd_xgbe,igb,tg3
r8169                  77824  0 
realtek                16384  3 
slhc                   16384  1 ppp_generic
tg3                   155648  0 
tunnel6                12288  1 ip6_tunnel
```

tunnel6 / ip6_tunnel is needed for provider used DS-Lite. OpenWRT needs a ds-lite package in userspace, but that isn't needed in BurmillaOS "core" because could / should be done by a system container.

**Comment by olljanat** [comment]
> Hardware APU / IPU boards from pcengines for example.

Those looks to be EOL https://www.pcengines.ch/eol.htm 

I have need to update home router/wlan access point to something which supports wi-fi 6 and it would be of course nice if it can run BurmillaOS so proposals for hardware are very welcome.

Banana Pi BPI-R3 is one of the options but it have only 2GB RAM and it requires ARM64 support which I have considered to drop from 2.0 unless we find someone who is ready to maintain it.

**Comment by pwFoo** [comment]
IPU board? https://www.ipu-system.de/

**Comment by olljanat** [comment]
@pwFoo did you btw tried to setup PPP with BurmillaOS? As far I see those modules are already part of kernel-extras

**Comment by pwFoo** [comment]
Hi @olljanat Thanks! Haven't seen that it's part of kernel-extras...

At the moment looks like old system-/user-docker causes problems with some nodejs applications. So need a way to a up to date docker version or build my ppp gateway with other os? 
But at the moment just no time to do some ppp tests with rancheros...

**Comment by olljanat** [comment]
Closing because [v2.0.0-rc1](https://github.com/burmilla/os/releases/tag/v2.0.0-rc1) was released and it have new enough Docker version.
