### ISSUE TITLE
TrueNAS Core 13 compatibility

### ISSUE THREAD

**Issue by bernieke** [burmilla/os#154]
**BurmillaOS Version: (ros os version)**
v1.9.6

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
TrueNAS Core 13.0-U3 (bhyve)

**Which processor architecture you are using?**
amd64

**Do you use some extra hardware? (GPU, etc)?**
no

Some background:

FreeNAS 11 (TrueNAS's predecessor) came with a "docker VM host" capability, using RancherOS inside a bhyve VM.

These virtual machines can't be upgraded (they boot using grub from the FreeBSD side), and in TrueNAS the capability has meanwhile been removed. Which means these VMs are permanently stuck at RancherOS v1.4.2.

So I'd like to recreate these using the standard TrueNAS VM capability and BurmillaOS.

But I'm failing to get a virtual machine to even boot from the iso. UEFI reports `BdsDxe: failed to load Boot0001 "UEFI BHYVE SATA DVD ROM BHYVE-BF16-952A-68C5" from PciRoot(0x0)/Pci(0x3,0x0)/Sata(0x0,0xFFFF,0x0): Not Found`.

I've tried various options to create the VM, but only the "UEFI" boot method supports VNC, and I'm not getting anything on the serial console using either the "UEFI-CSM" (legacy BIOS) or "Grub" methods.

**Comment by olljanat** [comment]
That UEFI issue is not expected to be solved on anytime soon. However if you have existing working RancherOS installation then you should be able to upgrade it by following https://burmillaos.org/docs/installation/upgrading/#upgrade-rancheros-to-burmillaos

**Comment by olljanat** [comment]
Ok. How you originally did that RancherOS installation?

**Comment by bernieke** [comment]
I didn't. It was a "docker host VM" feature FreeNAS had for a while. You just had to click a button to get a rancheros VM (pre-installed).

**Comment by olljanat** [comment]
Ok. Any idea about which version of FreeNAS it was then? (or which year so we can guess version)?
FreeNAS old versions looks to be still available on https://download.freenas.org/ and http://archive.freenas.org/

because if we want to make sure that upgrade from old version to latest works we need use same grub config location here.

**Comment by bernieke** [comment]
FreeNAS 11.2 seems to have been the latest version with the feature. It was removed in 11.3

**Comment by olljanat** [comment]
Found actually their PR which originally added that feature https://github.com/truenas/middleware/pull/374 and their OS images looks to be stored to http://download.freenas.org/bhyve-templates/

What I didn't found yet is that how those images are building but most probably we cane guess it by checking their content.
