### ISSUE TITLE
Udev rules not loaded after restart

### ISSUE THREAD

**Issue by toussii** [burmilla/os#155]
**BurmillaOS Version: (ros os version)**
v2.0.0-beta6
**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal
**Which processor architecture you are using?**
amd64
**Do you use some extra hardware? (GPU, etc)?**
no
**Which console you use (default, ubuntu, centos, etc..)**
default
**Do you use some service(s) which are not enabled by default?**
no
**Have you installed some extra tools to console?**
no
**Do you use some other customizations?**
no

I try to change the udev rules so created the following config.yml:

#cloud-config
bootcmd:
- [ touch, /etc/udev/rules.d/99-usb-serial.rules ]
- echo "SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", SYMLINK+="ttyUSB-RFX433"" > /etc/udev/rules.d/99-usb-serial.rules

This creates a symlink for this specific usb device. To reload these changes I run the following command:
sudo system-docker exec -it udev udevadm trigger

The problem is these changes are not saved and I need to run this command if the machine reboots. Is it possible to automate this?

**Comment by olljanat** [comment]
Try with https://burmillaos.org/docs/configuration/advanced/write-files/

**Comment by toussii** [comment]
Yeah did try that but it didn't work (with and without sudo):

#cloud-config
bootcmd:
- [ touch, /etc/udev/rules.d/99-usb-serial.rules ]
- echo "SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", SYMLINK+="ttyUSB-RFX433"" > /etc/udev/rules.d/99-usb-serial.rules

write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      system-docker exec -it udev udevadm trigger

**Comment by olljanat** [comment]
I mean that instead of whole bootcmd thing you provably should use write file for that file.

If it is not enough then maybe you need restart udev container in rc.local. Sudo is not needed on those

**Comment by toussii** [comment]
that is also not working :(

`#cloud-config
write_files:
  - path: /etc/udev/rules.d/99-usb-serial.rules
    permissions: "0755"
    owner: root
    content: |
      SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", SYMLINK+="ttyUSB-RFX433"
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      system-docker exec -it udev udevadm trigger`

**Comment by olljanat** [comment]
Perhaps it just run too early. Try add `wait-for-docker` to rc.local before that udev command.

**Comment by toussii** [comment]
Resolved the issue did run some logging and found that I need to remove the -i option because script is not a interactive terminal. Also the rule needs to be created inside the system-docker udev container. This is the working example:

#cloud-config
write_files:
  - path: /etc/udev/rules.d/99-usb-serial.rules
    container: udev
    permissions: "0755"
    owner: root
    content: |
      SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", SYMLINK+="ttyUSB-FTDI"
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      system-docker exec -t udev udevadm trigger > /var/log/boot/udev.log 2>&1
