### ISSUE TITLE
How to install burmillaOS and have it boot within Qubes?

### ISSUE THREAD

**Issue by therealjr** [burmilla/os#162]
**BurmillaOS Version: (ros os version)**

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Inside of a Qubes domU.

**Which processor architecture you are using?**
intel

**Do you use some extra hardware? (GPU, etc)?**
no
**Which console you use (default, ubuntu, centos, etc..)**
ubuntu
**Do you use some service(s) which are not enabled by default?**

**Have you installed some extra tools to console?**

**Do you use some other customizations?**

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
<replace with sudo ros config export output>
```

The install appeared to work in that I used make after pulling the project, everything is installed and the docker images are installed. But nothing is running. How do I get it to run? When I run the os docker container it just starts up, runs some tests, and then spins back down.

**Comment by olljanat** [comment]
Which version you are using?

Can you test with [v2.0.0-rc1](https://github.com/burmilla/os/releases/tag/v2.0.0-rc1)?

If that does not help then docker, dmesg logs would be useful. Afaik QubesOS is Xen based and I'm not sure if RancherOS ever was tested on that platform so we might miss some drivers, etc.

**Comment by therealjr** [comment]
Thanks for your reply. Let me be more clear. I used the most recent release of Burmilla OS but I did not install it within qubes from the iso file. I used an ubuntu template OS and compiled/installed Burmilla OS. I thought this would somehow dockerize the OS itself, but it did not.

**Comment by therealjr** [comment]
I will give more details later when I get home and can answer the version question. But it is the most recent version, I just pulled it from github.

**Comment by therealjr** [comment]
So, I tried to use 'ros os version' and it says command not found, which is weird because I installed ros-noetic-ros-core in order to get everything else to install.

**Comment by olljanat** [comment]
> I used an ubuntu template OS and compiled/installed Burmilla OS. I thought this would somehow dockerize the OS itself, but it did not.

Sounds that you are trying to do something very odd. Just do installation from ISO instead of or if you need image then run installation example on qemu VM and copy that disk image to Qubes.

**Comment by therealjr** [comment]
I cannot do an installation from ISO in this environment because there are drivers that need to be installed in order to be managed from the qubes interface.

**Comment by olljanat** [comment]
Which drivers? In general there is no supported way to install 3rd party drivers to BurmillaOS. Those need to be included in kernel build place and we have included those widely already. Especially in latest RC which I asked you to try.

However some of them requires enabling kernel-extras package.

**Comment by olljanat** [comment]
> Can you test with [v2.0.0-rc1](https://github.com/burmilla/os/releases/tag/v2.0.0-rc1)?

I can confirm it works fine on QubesOS 4.1.2. 

> How to install burmillaOS and have it boot within Qubes? 

1. Create it as standalone VM like described in https://www.qubes-os.org/doc/standalones-and-hvms/
2. Set *Kernel* to *Provided by qube*
3. Set *Initial memory* to *1024 MB*
4. Boot from ISO
5. Install to disk with command: `sudo ros install -d /dev/xvda --append rancher.password=Qwerty7`
6. Boot from disk.
7. Configure networking like described in https://burmillaos.org/docs/networking/

However, if you are looking full QubesOS integration then most likely BurmillaOS is wrong tool for you and you should use something like Debian instead of.
