### ISSUE TITLE
References in the docs

### ISSUE THREAD

**Issue by gramian** [burmilla/os#169]
**BurmillaOS Version: 2.0.0-rc1**

I am missing a reference section in the docs for:

* `ros` commands
* `ros config set` keys
* `cloud-init` properties

If there is indeed a need, I can help adding it.

**Comment by olljanat** [comment]
There is no any plans to document those more but contributions are of course welcome, just need to this about which level makes sense.

Easiest place to getting started most probably is #6
If those are not enough then just Google combination of "RancherOS" and your use case, there is hundreds examples available already.

Main config template is on https://github.com/burmilla/os/blob/v2.0.0-rc1/os-config.tpl.yml and full config on your installation you can see with command like `ros config export --full`
