### ISSUE TITLE
v2.0.0-rc2 missing in https://raw.githubusercontent.com/burmilla/releases/v2.0.x/releases.yml

### ISSUE THREAD

**Issue by netsandbox** [burmilla/os#171]
The rc2 release is missing in https://raw.githubusercontent.com/burmilla/releases/v2.0.x/releases.yml.

**Comment by olljanat** [comment]
Fixed by https://github.com/burmilla/releases/commit/aeb43f75625a33ffe77ab2d4d84b5a599621c8c3
