### ISSUE TITLE
Add docker-compose by default

### ISSUE THREAD

**Issue by tomaswarynyca** [burmilla/os#18]
>  And if possible, would be great to have docker-compose as part of the OS available as well

The user @x-jokay proposed in the issues #6 add by default docker-compose in BurmillaOS
We could create an option in the cloud-config.yml to enable docker-compose

**Comment by PrplHaz4** [comment]
I'd use this also - with the ability to update the version of compose as needed.  This might be more tricky than it seems as there is probably some redundancy with `ros service` - but migrating that to "plain" compose seems like an extra nice-to-have goal.

**Comment by olljanat** [comment]
It is very easy add docker-compose as system service.

Tricky part is get that how to command available inside of console container. Code contains some extra logic to handle it for user docker and we most likely need something similar.

This code makes user docker commands available to console:
https://github.com/burmilla/os/blob/0308bfe208060a9225e43bfb14a12581b2ee7a55/cmd/control/util.go#L36-L59
but I have not yet found that how container files gets visible to /var/lib/rancher/engine in first place.

**Comment by tomaswarynyca** [comment]
So by putting docker-compose in `/var/lib/rancher/engine/docker-compose` for example and making a symbolic link `/usr/bin/docker-compose` should the console recognize it?
