### ISSUE TITLE
Initramfs unpacking failed: uncompression error & kernel panic

### ISSUE THREAD

**Issue by Aerlin** [burmilla/os#19]
**BurmillaOS Version: (ros os version)**
burmillaos-v1.9.0-rc1

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

**Which processor architecture you are using?**
64bit Intel i5 650

**Do you use some extra hardware? (GPU, etc)?**
Don't believe so.

**Which console you use (default, ubuntu, centos, etc..)**
debian

**Do you use some service(s) which are not enabled by default?**
No

**Have you installed some extra tools to console?**
No 

**Do you use some other customizations?**
No

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
None
```

I came across BurmillaOS after seeing the news of RancherOS's EOL. My home server's running Proxmox. I tried creating a VM with 4GB of memory and ran burmillaos-v1.9.0-rc1.iso and burmillaos-v1.9.0-rc1-proxmoxve.iso. Both experience kernel panics on boot. 

I got some screenshots of the boot up messages.
https://i.imgur.com/5KH2Uwl.png

initramfs unpacking message
https://i.imgur.com/BEzsES5.png

kernel panic
https://i.imgur.com/0QIiYHo.png
https://i.imgur.com/CL9Z8Ih.png

I'm still able to boot rancheros-proxmoxve.iso (v1.5.6). I installed rancheros 1.5.6 and did the burmilla upgrade commands and it installed and rebooted fine.
```
sudo ros config set rancher.upgrade.url https://raw.githubusercontent.com/burmilla/releases/v1.9.x/releases.yml
sudo ros os upgrade
```

**Comment by olljanat** [comment]
@Aerlin Thanks for reporting this and welcome to BurmillaOS.

It looks like that we need more information from environment to be able to solve this issue.

First of all can you check that your ISO files are valid? Here is SHA256 checksums from versions which I just tested:
```
$ sha256sum *
386b9085e69878318617d0ba03aedb8c503a6ef4f2e95df9c444b6680c3d86c4  burmillaos-v1.9.0-rc1.iso
699fe91b7aeb23813070a515ea61da87af538ea590d0ea24df266ab189f816eb  burmillaos-v1.9.0-rc1-proxmoxve.iso
```

burmillaos-v1.9.0-rc1.iso boot without issues on my test lab with settings like these:
Guest OS:
- Type: Linux
- Version 5.x - 2.6 Kernel

CPU
- Sockets: 1
- Cores: 2

Memory (MiB): 2048  (I use very old laptop for testing for cannot use 4GB setting).

burmillaos-v1.9.0-rc1-proxmoxve.iso boot also without issues but with that one I also enabled "Qemu Agent" on System tab (as that ISO file will enable qemu-guest-agent by default.


> Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)
baremetal

I also wonder that what you mean by saying that you are using baremetal but then on other hand you are talking about Proxmox VE hypervisor?

**Comment by Aerlin** [comment]
Well, looks like I messed up. The ISOs have the correct sha256sum on my desktop, but after locating where Proxmox keeps its uploaded ISOs (/var/lib/vz/template/iso), the hashes were wrong. After reuploading, they have the correct sha256sum now and burmillaos-v1.9.0-rc1-proxmoxve.iso boots properly. Problem solved I guess. 


Apologizes, I misunderstood the Where are you running question. Thank you for the quick response olljanat.
