### ISSUE TITLE
Wanted: Maintainers

### ISSUE THREAD

**Issue by burmilla** [burmilla/os#2]
If we want keep Rancher OS alive by the community we will need 5-10 maintainers (I can be one of those but I don't want to be only one).

Most important task where we need maintainers is to have some one review, comment and approve pull requests when we get them. Anyone who is able to review code and is willing to sacrifice some of their time for better good can be maintainer.

We will also need agree pull request approval practice. My proposal is that anyone can create pull request and all pull requests much be reviewed by at least one maintainer and it must be different person than who created pull request (simple peer review practice to avoid human errors).

So anyone who is interest to be maintainer to this project please leave a comment.

**Comment by tomaswarynyca** [comment]
Hello, in view of the fact that RancherOS is going to be discontinued, I think the idea of creating a community version of it is excellent. I would like to be able to help with the project, I don't have much experience but I am willing to learn to improve the OS.

**Comment by olljanat** [comment]
@tomaswarynyca you are very welcome 👍
> Do you already have an organized means of communication for the organization of the collaborators?

 Not yet but you can reach me on Rancher Slack with same nick.

Anyway, can you start by sharing your use case(s) on https://github.com/burmilla/os/issues/6
and probably you want also check discussion about kernel versions on https://github.com/burmilla/os/issues/5

**Comment by ToeiRei** [comment]
count me in on giving you a hand as much as my time allows

**Comment by olljanat** [comment]
@tomaswarynyca @ToeiRei FYI, I did sent both of you now collaborator invitations from all Burmilla repos.

There is also now branch policy which require pull requests to be used to update master branch on all repos except os and os-services (because on those I'm actively working on now). I will add branch policy to those too after I got v1.9.0-rc1 ready.

**Comment by tomaswarynyca** [comment]
Great! Thank you for your confidence, I have finished accepting all applications.

**Comment by olljanat** [comment]
FYI. I added now branch policy to:
- https://github.com/burmilla/os/tree/v1.9.x
  - Branch which used to release v1.9.x versions and where each version code will be tagged.
- https://github.com/burmilla/os-services/tree/v1.9.0
  - Created based on v1.9.0-rc1 branch.
- https://github.com/burmilla/releases/tree/v1.9.x
  - Branch which we will which v1.9.x versions are using to check updates.

Policy will require changes to those branches going through pull request and someone else than he who created pull request to review and approve it (standard practice to avoid human errors).

**Comment by olljanat** [comment]
@tomaswarynyca @ToeiRei I noticed that it would be better that "burmilla" is GitHub organization than user account so I converted to it to like that based on https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/converting-a-user-into-an-organization now and invited both of you to be owners on it with me so you will get same access rights than I have.

Main purpose of that is to make sure that BurmillaOS can be maintained as long than at least one of us is able to participate.

**Comment by XiaodongLoong** [comment]
Hello, I am from Loongson (R & D CPU/mips64le), I wanna in.

**Comment by olljanat** [comment]
@XiaodongLoong Hi. I created feature request item to #23 with some basic infos. Feel free to add more information about that platform to there. Also note that you can reach us on Discord https://github.com/burmilla/os/issues/10#issuecomment-735303983

**Comment by KebinuChiousu** [comment]
@olljanat, @ToeiRei  I would be happy to help support Burmilla. I'm glad someone decided to support a fork of RancherOS. I'm a big fan of the low resource usage of this style and believe docker will still be around for a long time.

**Comment by olljanat** [comment]
@KebinuChiousu welcome, plz share your use case(s) on #6
We are just trying to finalize first release version and I'm trying to verify all known use cases on it.

**Comment by h8liu** [comment]
May I join too? We build [HomeDrive](https://www.homedrive.io) with depends (or depended) on RancherOS.

**Comment by olljanat** [comment]
@h8liu definitely, it is good to have people joining to project who have interest to keep it alive. If you have known issues/feature requests the please create them here so we can keep track of those.

@KebinuChiousu I just noticed that I have totally forgot you. Sorry about that.

I will contact both of you on Discord..

**Comment by wonleing** [comment]
I want to join in as a maintainer.
We (https://distrowatch.com/table.php?distribution=deepin) have a team here, aims to make a commercial distribution base on this opensource project. We can help to upgrade kernel and rootfs version with official source code, fix common bugs, add some non-secret arch support (say mips64el) code. While some custom kernel/rootfs changes and special arch support will be reserved. I think this can help both community and company.
I will update more detail on #6 and #78

**Comment by olljanat** [comment]
Everyone who is following this thread, please check my proposal as new architecture for BurmillaOS on #88

**Comment by olljanat** [comment]
> We (https://www.deepin.org/en/) have a team here, aims to make a commercial distribution base on this opensource project. We can help to upgrade kernel and rootfs version with official source code, fix common bugs, add some non-secret arch support (say mips64el) code. While some custom kernel/rootfs changes and special arch support will be reserved. I think this can help both community and company.

@wonleing very interesting. Can you point me to documentation how to build Deepin from sources codes? Probably we can share some tooling and build practices too.

**Comment by wonleing** [comment]
As far as I know, build Deepin from sources codes is not opened yet. But we have github opened: https://github.com/linuxdeepin/
You can find things there :)
