### ISSUE TITLE
Documentation should describe supported/non-supported use cases

### ISSUE THREAD

**Issue by olljanat** [burmilla/os#22]
Currently it is still bit unclear that which use case will be supported by BurmillaOS and key driver to define scope is feedback given on #6 

However I think that we can say for sure that:

These use cases are **not** supported:
- Kubernetes/K3s (because k3OS is made for those use cases)
- Rancher 2.x (because we do not support Kubernetes)
- Other Kubernetes specific tools

These use cases **are** supported:
- Standalone Docker containers (`docker run` / `docker create`)
- Multi-container Docker applications (`docker-compose`)
- Docker Swarm mode (`docker stack deploy` / `docker service`)

Also it is worth to mention that with "not supported" I mean that users are free to use BurmillaOS for those use cases if that works but any issues related to those will be considered to be on low priority.

**Comment by olljanat** [comment]
@tomaswarynyca @ToeiRei comments?

**Comment by ToeiRei** [comment]
Kubernetes is 'just a bunch of containers' and nothing we should really be scared of. I just wouldn't mention it as it doesn't need any special stuff (btw, I run K3s on rancherOS)

**Comment by olljanat** [comment]
> Kubernetes is 'just a bunch of containers' and nothing we should really be scared of.

On simple configuration yes but when it comes more complex setup there will be need to be persistent storage for /var/lib/kubelet and example Longhorn needs iscsid (look #21).

> (btw, I run K3s on rancherOS)

OK but notice that Rancher team made it very clear that they will not support K3s on RancherOS https://github.com/k3s-io/k3s/issues/173#issuecomment-620679654 Obviously they did know already then that RancherOS will be discontinued.

>  I just wouldn't mention it as it doesn't need any special stuff

Maybe we should then at least try explain recommend/tested use cases/configurations on documentation? Also BurmillaOS + K3s might make sense (on theory) on some specific use cases like on Raspberry Pi if k3OS will not support it.

**Comment by ToeiRei** [comment]
> Maybe we should then at least try explain recommend/tested use cases/configurations on documentation?

maybe something like 'We use it for.... ' to narrow it down a bit.
'We do not support...' or 'You must not...' are phrasings I'd like to avoid.

**Comment by olljanat** [comment]
> 'We do not support...' or 'You must not...' are phrasings I'd like to avoid.

Good point but we still should take care of the fact that BurmillaOS is based on Docker and now Kubernetes team is deprecating Docker support https://www.theregister.com/AMP/2020/12/03/docker_deprecated_in_kubernetes_this/

**Comment by tomaswarynyca** [comment]
> Describe supported/non-supported use cases

It seems correct to me to define the course of BurmillaOS. For the moment you should focus on the docker environment.
Support to @olljanat  that in the documentation it is necessary to define well for which use BurmillaOS is focused.

> Kubernetes is 'just a bunch of containers' and nothing we should really be scared of.

At the moment I don't see the need to put support for Kubernetes so he said @olljanat f will no longer support Docker as they 
are moving to ContainerD. 

> (btw, I run K3s on rancherOS)

If you like @ToeiRei  you can make a guide of how to use k3s in BurmillaOS but officially it's not a good idea to support it.v

**Comment by ToeiRei** [comment]
As docker support is now obsolete, we'can safely ignore that :)

**Comment by dgiebert** [comment]
As far as I understood RancherOS and therefore also BurmillaOS is built using Moby which uses containerd. You can verify this using:

```
ctr -n moby -a /run/docker/containerd/containerd.sock containers ls
```

I will keep an eye on this and make it work for Kubernetes if desired ?

**Comment by olljanat** [comment]
> As far as I understood RancherOS and therefore also BurmillaOS is built using Moby which uses containerd. 

True so as long user Docker/Moby comes with supported containerd version it might works (on theory).
You can check containerd version with command:
```bash
sudo ctr -n moby -a /run/docker/containerd/containerd.sock version
```
I also quickly checked that it updates if I switch to later Docker versions https://github.com/burmilla/os-services/pull/7

> I will keep an eye on this and make it work for Kubernetes if desired ?

Works for me as long it does not require big changes to BurmillaOS.

**Comment by laghoule** [comment]
Running K8S on RancherOS 1.5.6, installed via RKE. 
Ceph kernel module loaded

**Comment by olljanat** [comment]
FYI. Looks that Rancher have released tool called for k3d which looks to be nice way to play with k3s on BurmillaOS: https://rancher.com/blog/2020/set-up-k3s-high-availability-using-k3d

**Comment by olljanat** [comment]
Closing this one now because we need figure out answer to #47 first.

**Comment by olljanat** [comment]
For everyone who is planning to run Kubernetes on top of BurmillaOS on longterm. Please check my new architecture proposal on #88
