### ISSUE TITLE
We need new name (and logo) for community maintained Rancher OS

### ISSUE THREAD

**Issue by burmilla** [burmilla/os#3]
As far I'm aware of all Rancher OS components are using [Apache License 2.0](https://github.com/rancher-os-community/os/blob/community-dev/LICENSE) license which means that we can create community maintained version of Rancher OS but we need rename project as Rancher Labs, Inc own trademark "Rancher".

Directly quote from license file:
>    6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

Any ideas about new name?

You can also upvote others proposals by giving :+1: for those comments.

**Comment by olljanat** [comment]
> Since I think RancherOS makes a great homelab OS,

on https://github.com/rancher-os-community/os/issues/5#issuecomment-715530393 is very valid comment which why I was thinking that should we actually call this example for "Lab Container OS" (shortly on LCOS)? Then it would be clear for everyone that this cannot be considered to be production ready which gives us more flexibility to release new features.

PS. I'm still planning to keep this compatible with Rancher OS so any kernel/application upgrade published from here can be still installed to it (after those have been tested on good enough way).

**Comment by ToeiRei** [comment]
LabOS would be a nice name as it's short and sweet.

**Comment by olljanat** [comment]
@ToeiRei looks that LabOS name is already used by https://netlims.com/labos/ We most probably should try find some unique name.

**Comment by ToeiRei** [comment]
I've had a long walk and gave it some thoughts: Rancher has his names tailored around a ranch... Cattle, Longhorn, etc...
Do we want to keep the heritage in the name?

**Comment by PrplHaz4** [comment]
> 
> 
> I've had a long walk and gave it some thoughts: Rancher has his names tailored around a ranch... Cattle, Longhorn, etc...
> Do we want to keep the heritage in the name?

I think Docker and Rancher are both infringing words, so we probably have to be careful of getting too close, but it makes sense (to me) to acknowledge Rancher and/or Docker.

`d4ros` or `r5ros` (as a play on k8s - which is ultimately why RancherOS was abandoned), and a nod to docker which it's still very much dependent on, and Rancher Lab's spiritual successor to RancherOS - k3os

None of my google translate "ranch" or "dock" words in Finnish were easy (for me) to pronounce, but might make sense to honor the new BDFL (@olljanat)

**Comment by ToeiRei** [comment]
what about taking different animals from the ranch? I mean, they got cattle, why not take sheep or chicken?

**Comment by olljanat** [comment]
Good comments. I guess that name "Rancher" comes actually from [Pets vs Cattle](http://cloudscaling.com/blog/cloud-computing/the-history-of-pets-vs-cattle/) analogy. They founded company to provide tools which let users treat servers and containers like cattle.

Lab servers normally end up to be more or less pets so I renamed this GitHub organization now to [lemmikki](https://en.wiktionary.org/wiki/lemmikki) which is "pet" on Finnish (and looks to be also name of some flower) and created Docker Hub organization on same name as those looked to be free.

But that does not necessarily need to be final name if someone figure out better name so I guess that I will keep thinking about this still couple of days before start updating code match to new name.

**Comment by ToeiRei** [comment]
we could go for some pets then like CatOS as it is easier to get to people that way. Logo could be a kitten playing with a container...

**Comment by olljanat** [comment]
@ToeiRei that is option for sure. We just need find name which does no collide with existing solutions and have github+docker hub names free. Preferably with exact same name on both of those.

With quickly look these are at least reserved already
- [CatOS](https://en.wikipedia.org/wiki/Cisco_Catalyst#CatOS)
- [KittyOS](https://sourceforge.net/projects/kittyos/)
- [Puppy Linux](http://puppylinux.com/)

**Comment by ToeiRei** [comment]
then let's look for another pet. For sticking in peoples minds I would choose something english...

**Comment by olljanat** [comment]
@ToeiRei @PrplHaz4 What you think about name [burmilla](https://en.wikipedia.org/wiki/Burmilla) (cat breed)? That was free on both GitHub and Docker Hub so I reserved it now.

**Comment by ToeiRei** [comment]
` In temperament they are sociable, playful and affectionate and get along well with children and other animals.` Sounds like our tagline...

**Comment by PrplHaz4** [comment]
> 
> 
> @ToeiRei @PrplHaz4 What you think about name [Burmilla OS](https://en.wikipedia.org/wiki/Burmilla) (cat breed)? That was free on both GitHub and Docker Hub so I reserved it now.

Works for me!
