### ISSUE TITLE
v1.9.0 release tag instructions should switch to debian console

### ISSUE THREAD

**Issue by PrplHaz4** [burmilla/os#32]
**BurmillaOS Version: (ros os version)** 
v1.9.0

The instructions in the v1.9.0 tagged release says to switch console to `default`, but I believe it should be `debian`.
https://github.com/burmilla/os/releases/tag/v1.9.0

Current:

```bash
sudo ros console switch default
```

Update to:

```bash
sudo ros console switch debian
```

**Comment by olljanat** [comment]
Current instruction is correct. Build process always creates console with name default so I replaced its build files with Debian console content.

You can see it if you check history of files on https://github.com/burmilla/os/tree/master/images/02-console

On RancherOS extra consoles was build from os-services repository and we don't have those files there anymore.

Currently switching console is not even mandatory as default console works as fallback option but that is part of instructions just in case to avoid any weird behaviors.

**Comment by PrplHaz4** [comment]
> 
> 
> Current instruction is correct. Build process always creates console with name default so I replaced its build files with Debian console content.
> 
> You can see it if you check history of files on
> https://github.com/burmilla/os/tree/v1.9.x/images/02-console
> On RancherOS extra consoles was build from os-services repository and we don't have those files there anymore.
> 
> Currently switching console is not even mandatory as default console works as fallback option but that is part of instructions just in case to avoid any weird behaviors.

Ok great - I thought for some reason we had to switch to Debian first.

Any idea if there is anything lost or changed by a console switch (like init scripts) or anything that we should warn people about in the docs?

I will update the associated doc: https://github.com/burmilla/burmilla.github.io/edit/master/content/docs/installation/upgrading.md

**Comment by olljanat** [comment]
> Ok great - I thought for some reason we had to switch to Debian first.

Yea I think that it was beta2 version where I got some errors when updated from installation which was using Ubuntu console and it tried to re-enable it after upgrade.


> Any idea if there is anything lost or changed by a console switch (like init scripts) or anything that we should warn people about in the docs?

Good question. I think that OS upgrade has always resetted console to default settings (also on RancherOS I mean) because container is re-created from new image version but I'm not sure about that.

Would be good if someone can test different combinations. First by starting with non latest RancherOS with non default console, add some changes and upgrade to latest. Then same by upgrading to BurmillaOS and based that info we should update documentation.

**Comment by olljanat** [comment]
Interesting. I noticed that when upgrading OS with default console then console does not actually get upgraded unless user forces it. 

Result after upgrade:
```bash
$ sudo system-docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED              STATUS              PORTS               NAMES
3360e2f1e2f3        rancher/os-console:v1.5.6           "/usr/bin/ros entr..."   3 minutes ago        Up About a minute                       console
```

After upgrade:
```bash
$ sudo ros console switch default
WARN[0000] Console is already set to default
Switching consoles will
1. destroy the current console container
2. log you out
3. restart Docker
Continue [y/N]: y

$ sudo system-docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED              STATUS              PORTS               NAMES
210f3fe1c71e        burmilla/os-console:v1.9.0          "/usr/bin/ros entr..."   13 seconds ago       Up 12 seconds                           console
```

So we probably need mention extra `sudo ros console switch default` command on upgrade guide.

**Comment by tomaswarynyca** [comment]
@olljanat Which OS and version are you upgrading to burmilla?

The upgrade from RancherOS to BurmillaOS is already in the documentation
https://burmillaos.org/docs/installation/upgrading/#upgrade-rancheros-to-burmillaos
![image](https://user-images.githubusercontent.com/41587659/102354029-c0579700-3f88-11eb-8bbe-f4867ff27822.png)

**Comment by olljanat** [comment]
From 1.5.6 but it looks that console switch command need to actually run _after_ upgrade not before.
