### ISSUE TITLE
Strategy to update the zfs service to use openzfs

### ISSUE THREAD

**Issue by zimme** [burmilla/os#49]
I have a fork of os-services with zfs updated to both 0.8.6 and 2.0.1.

How do we want to handle this?

ZFSonLinux has rebranded to OpenZFS with version 2.0.0.

I could do a PR with the `zfs` services bumped to `0.8.6` and include a new service `openzfs` which will be using version `2.0.1`.

Or I could do a PR where I just bump the `zfs` service to version `2.0.1` directly.

From what I can tell, OpenZFS (2.0.1) can import older pools and you need to manually enable any new features that a later version bings (just as it's always been) so I guess we won't be breaking anyones zfs setup by bumping the `zfs` service to `2.0.1` directly.

Thoughts?

**Comment by olljanat** [comment]
I'm not familiar with zfs at all but based what you are saying it sounds that it is simplest just bump version to latest and test upgrade scenario.

We anyway have now [v1.9.1-rc1](https://github.com/burmilla/os/releases/tag/v1.9.1-rc1) testing on going so I think that it simplest if you can create PR against of **v1.9.1-rc1** branch on os-services so it can be used to test upgrade scenario.

Upgrade command to RC version is (image must be defined because it is not marked as latest):
```
sudo ros os upgrade -i burmilla/os:v1.9.1-rc1
```

**Comment by zimme** [comment]
PR sumitted. https://github.com/burmilla/os-services/pull/13

**Comment by olljanat** [comment]
Build https://github.com/burmilla/os-services/runs/1724229423 passed so now updated version should be available on v1.9.1-rc1 (it might need `sudo ros service list --update` before visible).

**Comment by zimme** [comment]
I actually had to manually update the config `rancher.repositories.core.url` to `https://raw.githubusercontent.com/burmilla/os-services/v1.9.1-rc1` as that wasn't updated after running `sudo ros os upgrade -i burmilla/os:v1.9.1-rc1`.

Otherwise a service list --update or a service pull zfs still pulled 0.7.13-1 of zfs.

**Comment by olljanat** [comment]
Hmm. So I assume that if you run `sudo system-docker ps ` it show that console is still on earlier version?
.
That is kind of feature that we do not reset console changes automatically but probably we should then force new value to `rancher.repositories.core.url`

**Comment by zimme** [comment]
Yeah that's correct. It's still on 1.9.0 for the console and I guess that's why the repositories url hasn't been updated?

**Comment by tomaswarynyca** [comment]
The URL must be https://raw.githubusercontent.com/burmilla/releases/v1.9.x/releases.yml
Then run **sudo ros os upgrade -i burmilla/os:v1.9.1-rc1** to upgrade

**Comment by zimme** [comment]
@tomaswarynyca That's the upgrade url and not the repository url. The upgrade went fine. It was just that the repositories core url wasn't updated to 1.9.1-rc1 and because of that I wasn't able to pull the latest zfs service.

**Comment by olljanat** [comment]
Yeah this is good example of the reasons why I wanted to drop all other consoles as on RancherOS there was too many options so all them are not correctly tested.

On RancherOS default console was non-persistent but most probably this issue have been on all alternative consoles for years.

**Comment by zimme** [comment]
Could we find a way of only persisting some paths of the console so that the home folder and some apt related stuff are saved to have the console always be the latest but have it automatically reinstall apt packages and keep home dir stuff?

**Comment by tomaswarynyca** [comment]
> @tomaswarynyca That's the upgrade url and not the repositories core url. The upgrade went fine. It was just that the repositories core url wasn't updated to 1.9.1-rc1 and because of that I wasn't able to pull the latest zfs service.

Uhh I'm asleep sorry, I read anything heh

**Comment by tomaswarynyca** [comment]
> Could we find a way of only persisting some paths of the console so that the home folder and some apt related stuff are saved to have the console always be the latest but have it automatically reinstall apt packages and keep home dir stuff?

It seems like a good idea to me, just yesterday I updated my server and noticed that the installed things were deleted

**Comment by zimme** [comment]
Maybe let's have the console discussion in a new issue. I'm running zfs 2.0.1 on v1.9.1-rc1 now so this could be closed i guess.

**Comment by olljanat** [comment]
> Could we find a way of only persisting some paths of the console so that the home folder and some apt related stuff are saved to have the console always be the latest but have it automatically reinstall apt packages and keep home dir stuff?

Reopened https://github.com/burmilla/os/issues/48 for that discussion.

Anyway, did the ZFS works correctly after upgrade or are still doing more testing?

**Comment by zimme** [comment]
Yeap, so far it seems to work. Will write an update if things crash.
