### ISSUE TITLE
Change restart/shutdown logs

### ISSUE THREAD

**Issue by tomaswarynyca** [burmilla/os#51]
When doing **sudo poweroff** or **sudo reboot** the logs are not displayed correctly, nothing is understood. 
The process logs add dots as they are executed which causes the display to be garbled.

![image](https://user-images.githubusercontent.com/41587659/105360689-a0467380-5bd7-11eb-92e7-76897a3bb72f.png)

**Comment by olljanat** [comment]
Afaiu those dots are coming from kernel/init process after console container has stopped. Might be tricky to fix.
