### ISSUE TITLE
Hostname in /etc/hostname is incorrect

### ISSUE THREAD

**Issue by olljanat** [burmilla/os#52]
**BurmillaOS Version: (ros os version)**
v1.9.1-rc1

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Nutanix AHV

**Which processor architecture you are using?**
amd64

Not sure yet it if this is bug on Burmilla or just issue on way how we deploy these servers but I noticed that after a while `/etc/hostname` value ends up to be "burmilla"
```
$ hostname && cat /etc/hostname
olli-test.lab.local
burmilla
```

Have seen this only on latest RC so far. Changed between it and latest release version can be seen on https://github.com/burmilla/os/compare/v1.9.0...v1.9.1-rc1

**Comment by olljanat** [comment]
This is most probably same than https://github.com/rancher/os/issues/2759 so it is old issue.

@h8liu @KebinuChiousu can you investigate this one? It might be that root cause is just too old dhcpd (which comes from [os-base](https://github.com/burmilla/os-base)). If that is case then we shouldn't be able to reproduce it on v2.0.0 beta versions because there OS base is updated. Unfortunately we cannot update os-base to v1.9.x (or at least to latest version) because on that combination boot failed to "Kernel is too old" error.

**Comment by h8liu** [comment]
How to reproduce this? Is this on an upgrade or a new install?

I have many instances upgraded from rancher os to burmilla 1.9.1, but I do not see these issues.

**Comment by olljanat** [comment]
My ones was all new installation. Reproduce guide looks to be available on https://github.com/rancher/os/issues/2759#issuecomment-501312149
