### ISSUE TITLE
Remove rancheros from boot menu

### ISSUE THREAD

**Issue by psychowood** [burmilla/os#53]
Hi,
I've just upgraded from rancherOs 1.5.7 quite smoothly, everything seems to work as expected 👍 and I already purged all the unused rancher images

In the boot menu I still see rancherOS tho, can you tell me how to remove it?

Edit: since I'm here, what's the correct way to rename/migrate the "rancher" user?

Thanks!

**Comment by olljanat** [comment]
RancherOS should disappear from boot menu after you next time upgrade BurmillaOS as it always contains current and previous version.

Because of backward compatibility admin user still called for "rancher" shouldn't be renamed.
