### ISSUE TITLE
Best/correct way to relocate /var/lib/docker for user-docker

### ISSUE THREAD

**Issue by psychowood** [burmilla/os#54]
**BurmillaOS Version: (ros os version)**
1.9.0

I'm trying to move the docker folder to another partition, mostly because burmilla is currently running on a very small VM and I'd like to preserve the disk space.

In a standard linux distribution, my usual way is stop docker, rsync /var/lib/docker to the new destination, either change the data-root path or directly symlink the old folder to the new location.

I'm not sure how to achieve this because of the volumes structure.

AFAIU, container `docker` has `/var/lib/user-docker` mapped to `/var/lib/docker` that is owned by the container `container-data-volumes`. Needless to say`/var/lib/user-docker` is not available from the burmilla console.

Thanks!

**Comment by olljanat** [comment]
You can either extend disk https://burmillaos.org/docs/configuration/advanced/resizing-device-partition/

Or use runcmd command like we do https://github.com/burmilla/os/issues/6#issuecomment-715916407 to mount /var/lib/docker before user docker starts.

Actual relocation you should be able to do by stopping user docker `sudo system-docker stop docker` first and then starting shell deeper in system with command like `sudo system-docker-it --rm -v /:/host bash bash`

**Comment by psychowood** [comment]
Disk extension/formatting is not really an option (or better, it is the last one) since I have already allocated the disk and my ESXi datastore is pretty full.

I managed to do it starting from your suggestions, here's my message for posterity:

1. prepare a mount point where you want to move the user-docker folder, e.g. `/mnt/my-user-docker` (in my case it's a btrfs subvolume), and keep track of the mount command used e.g. 
`mount -t btrfs /dev/disk/by-uuid/xxx /mnt/my-user-docker -o subvol=user-docker`
2. stop all the user containers and user-docker itself
`sudo system-docker stop docker`
3. enter the host folder with a shell of your choice (i used [instrumentisto/rsync-ssh](https://hub.docker.com/r/instrumentisto/rsync-ssh)), mapping both the host directory and your target one. 
`sudo system-docker run -it --rm -v /:/host -v /mnt/my-user-docker:/tmp-user-docker instrumentisto/rsync-ssh /bin/sh`
4. copy the old folder to the new one
`rsync -aPv /host/var/lib/user-docker/ /tmp-user-docker/`
5. rename the old folder to be sure you are not using it anymore
`mv /host/var/lib/user-docker /host/var/lib/user-docker.bak`
6. `exit` the inner shell
7. prepare a file, lets say `my-user-docker-mount.yml` to add the new mount command to your configuration, using the same command at point **1.** with the exception of mounting it to `/var/lib/docker` 
Gentle reminders: 
7.1. **the following one is just an example for my configuration, TO NOT blind copy it**
7.2. **check with `sudo ros config export` if you already have some `runcmd` defined: in that case you have to keep them in the new file otherwise you may end up with a broken system**
```yaml
runcmd:
- - mount
  - -t
  - btrfs
  - /dev/disk/by-uuid/xxx
  - /var/lib/docker
  - -o
  - subvol=user-docker
```
8. merge the file in your configuration
`cat my-user-docker-mount.yml | sudo ros config merge`
9. check that everything is in place running again
`sudo ros config export`
10. reboot
`sudo reboot`
12. **Profit!**
13. If everything works, you can enter the inner shell again (point **3.** ) and remove the backed up directory 
`rm -rf /host/var/lib/user-docker.bak`

Thanks @olljanat !
