### ISSUE TITLE
Add to releases a format supported by Digital Ocean

### ISSUE THREAD

**Issue by Exadra37** [burmilla/os#55]
https://www.digitalocean.com/docs/images/custom-images/#image-requirements

> Image Requirements
>
>Images you upload to DigitalOcean must meet the following requirements:
>
>    Operating system. Images must have a Unix-like OS.
>
>    File format. Images must be in one of the following file formats:
>        Raw (.img) with an MBR or GPT partition table
>        qcow2
>        VHDX
>        VDI
>        VMDK
>
>    Size. Images must be 100 GB or less when uncompressed, including the filesystem.
>
>    Filesystem. Images must support the ext3 or ext4 filesystems.
>
>    cloud-init. Images must have cloud-init 0.7.7 or higher, cloudbase-init, coreos-cloudinit, ignition, or bsd-cloudinit installed and configured correctly. If your image's default cloud-init configuration lists the NoCloud datasource before the ConfigDrive datasource, Droplets created from your image will not function properly.
    Click here to display detailed cloud-init instructions.
>
>    SSH configuration. Images must have sshd installed and configured to run on boot. If your image does not have sshd set up, you will not have SSH access to Droplets created from that image unless you recover access using the Droplet console.
>
> You can also upload a custom image that meets the above criteria as a compressed gzip or bzip2 file.

**Comment by olljanat** [comment]
First of all, please share your use case details on https://github.com/burmilla/os/issues/6

Secondly you can create Digital Ocean version of image using https://github.com/burmilla/os-packer

Most probably we will not add any Cloud images to releases automatically because it is better that people are able to modify settings like disk size when they build image they selves.

**Comment by Exadra37** [comment]
Maybe adding the link for `os-packer` into the README of this project will be enough to direct people in the right direction?

**Comment by andrewvmail** [comment]
I managed to pack burmilla with packer and created a qcow2 using repo mentioned, boot into it fine too in DO. this might help people.

Steps taken:

get a machine from do and ssh in

```
# 129643249 = ubuntu docker image in digitalocean
doctl compute droplet create --image 129643249  --size  m3-4vcpu-32gb --region sfo3 builder.example.com --ssh-keys 1234578,234566 --droplet-agent=false
```
ssh into above machine after its provisioned
```
ufw disable
git clone https://github.com/burmilla/os-packer.git
cd os-packer
cd digitalocean/
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update && sudo apt install packer
apt-get install qemu-kvm
# modify the ram to 16G faster build
# change the image path rancheros.iso to ./rancher.iso
vim digitalocean-qemu.json
wget -O rancheros.iso https://github.com/burmilla/os/releases/download/v1.9.7-rc1/burmillaos-v1.9.7-rc1.iso
ISO_CHECKSUM=aa917a53e67ef8150f1015031777b0ea PACKER_BOOT_WAIT=180s PACKER_LOG=1 packer build
```

# changes made to digitalocean-qemu.json
```
-      "iso_url": "/rancheros.iso",
+      "iso_url": "./rancheros.iso",
       "name": "digitalocean",
       "net_device": "virtio-net",
       "qemuargs": [
         [
           "-m",
-          "1400M"
+          "16G"
         ],
```

scp the image out and upload it to digitalocean
```
scp root@xxx.xxx.xxx.xxx:/root/os-packer/digitalocean/output-digitalocean/packer-digitalocean ~/Desktop/.
```
