### ISSUE TITLE
BurmillaOS :)

### ISSUE THREAD

**Issue by pwFoo** [burmilla/os#57]
Hi, 
I'm still using RancherOS and happy to see active developed and maintenanced BurmillaOS! 👍 
After some backups I'll try to migrate from RancherOS 1.5.6 to BurmillaOS :)

RancherOS was server focused, but it would be also a great desktop linux distribution. Do you plan to add some desktop related features (kernel and modules)?

**Comment by olljanat** [comment]
Currently there is no plans like that but I wonder that why you are asking about it?

What would be the use case which is not already handled better by some other Linux distribution?

Main purpose for RancherOS/BurmillaOS is minimize overhead needed by Docker (Swarm) platform which makes big difference on environments which are running hundreds of Docker Swarm nodes on top of virtualization platform.

**Comment by pwFoo** [comment]
I know RancherOS kernel-extras (?) package which created for desktop usage. I forgot what was still missing...

I played with docker desktop (xorg, fluxbox, chrome,...). All applications in docker containers :)

**Comment by olljanat** [comment]
> I played with docker desktop (xorg, fluxbox, chrome,...). All applications in docker containers :)

Aha! You mean something like this? https://medium.com/better-programming/running-desktop-apps-in-docker-43a70a5265c4

> I know RancherOS kernel-extras (?) package which created for desktop usage. I forgot what was still missing...

Sure we can add more modules to kernel-extras. Just let us know if you figure what is missing.

**Comment by pwFoo** [comment]
Yes, all applications / parts in a own container. Simple setup worked fine some time ago and I stopped playing with that setup because of soome problems. It was related to RancherOS but con't remember why...

I think we can close that issue for now. If I need help I open a new one.

Thanks for maintain that fork of RancherOS, I really love the way it works and still it's no option to switch to k3os, podman or kubernetes...

👍
