### ISSUE TITLE
Update Docker version and move from rancher/os-docker to burmilla/os-docker

### ISSUE THREAD

**Issue by PrplHaz4** [burmilla/os#7]
Capturing this here until it's no longer needed...

**RancherOS Version: (ros os version)**
1.5.6

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
NA

Courtesty of @olljanat @ https://github.com/rancher/os/issues/3000#issuecomment-714525623

> 
> 
> I did build now later Docker versions than currently are available on official version. You can use those like this.
> 
> First set new repository location:
> 
> ```shell
> sudo ros config set rancher.repositories.docker.url https://raw.githubusercontent.com/rancher-os-community/os-services/master
> ```
> 
> Then you can switch to latest Docker using commands 19.03.13:
> 
> ```shell
> sudo system-docker pull rancheroscommunity/os-docker:19.03.13
> sudo system-docker tag rancheroscommunity/os-docker:19.03.13 rancher/os-docker:19.03.13
> sudo ros engine switch docker-19.03.13
> ```
> 
> or if you want to test Docker 20.10.0-beta1 version you can do it with commands:
> 
> ```shell
> sudo system-docker pull rancheroscommunity/os-docker:20.10.0
> sudo system-docker tag rancheroscommunity/os-docker:20.10.0 rancher/os-docker:20.10.0-beta1
> sudo ros engine switch docker-20.10.0-beta1
> ```

**Comment by olljanat** [comment]
We will need update BurmillaOS guide https://burmilla.github.io/upgrading/ in https://github.com/burmilla/burmilla.github.io/blob/master/upgrading/README.md to containing this info.

It is very boring that currently we need manually pull and tag images.
Need to investigate where this value actually is stored on RancherOS installation so we can update it.
https://github.com/burmilla/os/blob/2ec7f4fc9ee35132804997db6eb47826fcd4b393/Dockerfile.dapper#L57

**Comment by olljanat** [comment]
Upgrade from RancherOS to BurmillaOS works now on [1.9.0-beta2](https://github.com/burmilla/os/releases/tag/v1.9.0-beta2) with these commands:
```
sudo ros config set rancher.upgrade.url https://raw.githubusercontent.com/burmilla/releases/v1.9.x/releases.yml
sudo ros os upgrade
```

**Comment by ToeiRei** [comment]
I just did the update and it looks good so far. Any plans on putting that info into a wiki or readme as new volunteers may struggle to find that stuff in the issues?

**Comment by olljanat** [comment]
We I have made copy of RancherOS documentation to https://github.com/burmilla/burmilla.github.io and rendered version is automatically published to https://burmilla.github.io

Biggest issue with that one is that we lost navigation when I removed Rancher layout from it so we need fix that first and then we can start updating documentation.

**Comment by olljanat** [comment]
FYI. Docker version 19.03.14 and 20.10.0 (release version) are now available for testing https://github.com/burmilla/os-services/pull/7

**Comment by olljanat** [comment]
Now we have working documentation site so this should be updated to https://github.com/burmilla/burmilla.github.io/blob/master/content/docs/installation/upgrading.md

**Comment by olljanat** [comment]
Documented on https://burmillaos.org/docs/installation/upgrading/
