### ISSUE TITLE
Feature Request: make BurmillaOS replacing Rancher with  Hetzner Cloud

### ISSUE THREAD

**Issue by AltB** [burmilla/os#70]
With  Hetzner Cloud (a European mid-size "cloud provider"), you can boot your VPS on RancherOS.
It would be nice to make BurmillaOS known as RancherOS fork. The name BurmillaOS is not very meaningful without connection with Rancher (Rancher was a well-known and reassuring brand). It could good be good for BurmillaOS.

![image](https://user-images.githubusercontent.com/3625513/112961115-5b920800-9145-11eb-92d2-c9d113afae49.png)

**Comment by olljanat** [comment]
> With Hetzner Cloud (a European mid-size "cloud provider"), you can boot your VPS on RancherOS.
> It would be nice to make BurmillaOS known as RancherOS fork.

BurmillaOS is fully community based fork so anyone who have connections to Hetzner Cloud can propose this for them.

> The name BurmillaOS is not very meaningful without connection with Rancher (Rancher was a well-known and reassuring brand). It could good be good for BurmillaOS.

Separation from Rancher name and brand was done on purpose because Rancher Labs own brand "Rancher" and because BurmillaOS is not supported OS for their products.
