### ISSUE TITLE
BurmillaOS on ARMv7 and as LXC Container for Turris Omnia Router

### ISSUE THREAD

**Issue by x0tester0x** [burmilla/os#75]
I want to run BurmillaOS on the Turris Omnia Router, which has a Marvell Armada 385, dual-core 1.6 GHz CPU, but does only support LXC Containers([https://docs.turris.cz/geek/lxc/lxc](https://docs.turris.cz/geek/lxc/lxc)).

**Comment by olljanat** [comment]
That is not doable. LXC containers support is out of scope for BurmillaOS and we support only 64 -bit CPUs where ARMv7 only supports 32 -bit.

Nearest option of that is run BurmillaOS 2.x (only beta versions of it currently exist) on Raspberry Pi 4B which have 64 -bit ARMv8 CPU.

**Comment by x0tester0x** [comment]
Ok, but as LXC Container on on a ARMv8 CPU?

**Comment by olljanat** [comment]
There is no any plans to support LXC containers on BurmillaOS.
