### ISSUE TITLE
RancherOS load / I/O problems

### ISSUE THREAD

**Issue by pwFoo** [burmilla/os#80]
I still use RancherOS and really need to migrate to BurmillaOS...

Experienced some times problems with load / io!
During docker pull / docker swarm deploy (with images needed to pull) system gets sluggish. Also some times I open a document with my nextcloud load increases to >100! Need to kill some processes / containers to get the load down again.
```
rancher:~$ top
Mem: 3527904K used, 514444K free, 335912K shrd, 4260K buff, 431652K cached
CPU:   0% usr   5% sys   0% nic   0% idle  95% io   0% irq   0% sirq
Load average: 116.45 58.01 23.13 2/1760 6403
```

I hope it's related to RancherOS (updated from older versions many times) and not latest RancherOS / BurmillaOS...
But would be interested to know if anyone else is affected with such load / io problems?

**Comment by pwFoo** [comment]
Looked into user docker containers. user docker died I think. Update of all containers is just some minutes since I noticed load of 116 increasing...

**Comment by olljanat** [comment]
Does not sound familiar. From which version you upgraded?
Also did you run `sudo ros console switch default` command after upgrade (console does not get upgraded other why) like it is on guide? https://burmillaos.org/docs/installation/upgrading/#upgrade-rancheros-to-burmillaos

**Comment by olljanat** [comment]
Moving this comment to here from: https://github.com/burmilla/os/pull/87#issuecomment-827158055
> Maybe scheduler is the cause of my io problems. Pull images will slow down my VM.
> It was improved by migration to BurmillaOS (with docker update) and I think / hope scheduler adjustment will give me another push 👍

@pwFoo Which version you are now using? v1.9.1?

> Looked into user docker containers. user docker died I think...

I did see similar issues on machines which did run out of memory #33 and that was improved on v1.9.1 with this change #35

**Comment by pwFoo** [comment]
Yes, I switched console. All works fine or better as before after migration. Reduced load, io wait and better docker pull performance. 
VM died some times before I migrated and with BurmillaOS problems have been greatly reduced.

Maybe scheduler could improve io wait. But updated user docker was a big point I think.

**Comment by pwFoo** [comment]
Migrated to apu systems to BurmillaOS to. i/O performance is much better than RancherOS, but still not perfect.
Maybe related to scheduler or the (user-)docker in (system-)docker setup?
Image pull is a little bit slow and I see i/o wait during pulls.

But I think BurmillaOS with newer (user-)docker is a great improvement to the performance! 

I close that issue for now
