### ISSUE TITLE
User images in xz format not loading

### ISSUE THREAD

**Issue by ashutoshbbpandey** [burmilla/os#97]
**BurmillaOS Version: v 1.9.1**

**Where are you running BurmillaOS? VMware**

**Which console you use (default, ubuntu, centos, etc..) : default**

**Do you use some service(s) which are not enabled by default?: no**

**Have you installed some extra tools to console?: no**

**Do you use some other customizations?: no**

While pre-loading user image in tar.xz compression not able to load complaining could not find xz-utils in path. In documentation, it is mentioned that xz and gzip format is supported for user image preloading, then why it is looking for xz-utils?

**Comment by olljanat** [comment]
Sound weird. How exactly did installation? Also how much you have allocated RAM for it? IIRC VMware tools take quite a lot of memory which VMs with very small memory does not works.
