### ISSUE TITLE
Performance problem with non existing user-docker images?

### ISSUE THREAD

**Issue by pwFoo** [burmilla/os#98]
Hi,

I don't know if it's releated to RancherOS / BurmillaOS, Docker Swarm or something else...

I run BurmillaOS in (User-)Docker Swarm mode and misspelled an image in compose file and triggered stack update. docker tried to pull the not existing image and update the running stack. Because of the non existing image defined in my compose console gets unresponsive and finally my ssh session ended / break.
Some time later login worked fine again, I updated and redeployed my stack.

Could it system-docker -> user-docker releated to increase load or i/o during redeploy without pre-pulled image?

**Comment by olljanat** [comment]
How many CPU cores and how much memory you have? Sounds like out of memory issue.

**Comment by pwFoo** [comment]
4GB RAM
2vCPU Cores

**Comment by olljanat** [comment]
Which hardware/hypervisor?

**Comment by pwFoo** [comment]
vmware

Image pulls / swarm deploy without local image slows down the system and established ssh sessions hang / lazy. It's much better since (user-)docker ist updated.

**Comment by olljanat** [comment]
Hmm. Sounds like issue which #36 tried to improve by adding 64 MB admin reservation. Maybe VMware needs bigger one.

Can you test by adding 128 MB or even 256 MB reservation `vm.min_free_kbytes: 131072` / `vm.min_free_kbytes: 262144` to sysctl? https://burmillaos.org/docs/configuration/advanced/sysctl/

**Comment by pwFoo** [comment]
Changed temp for testing.
```
sudo sysctl -w vm.min_free_kbytes=131072
```
